---
- name: Install PostgreSQL packages
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Enable and start PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    enabled: true
    state: started
